#############################################################################
# Makefile for building: basiclayouts
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  basiclayouts.pro
# Template: app
# Command: /opt/qt5.9.2/5.9.2/gcc_64/bin/qmake -o Makefile basiclayouts.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt5.9.2/5.9.2/gcc_64/include -I/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets -I/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui -I/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/qt5.9.2/5.9.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5.9.2/5.9.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5.9.2/5.9.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = basiclayouts1.0.0
DISTDIR = /u/data/u98/cs240/2017Fall/lab11-irc-gui-qt/lab11-src/layout2/.tmp/basiclayouts1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qt5.9.2/5.9.2/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/qt5.9.2/5.9.2/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dialog.cpp \
		main.cpp moc_dialog.cpp
OBJECTS       = dialog.o \
		main.o \
		moc_dialog.o
DIST          = /opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/spec_pre.prf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/unix.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/linux.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/sanitize.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/gcc-base.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/g++-base.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/qconfig.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/toolchain.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/resources.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/moc.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/uic.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/file_copies.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/lex.prf \
		basiclayouts.pro dialog.h dialog.cpp \
		main.cpp
QMAKE_TARGET  = IRCCLient
DESTDIR       = 
TARGET        = IRCCLient


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: basiclayouts.pro /opt/qt5.9.2/5.9.2/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/spec_pre.prf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/unix.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/linux.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/sanitize.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/gcc-base.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/g++-base.conf \
		/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/qconfig.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/toolchain.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/default_pre.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/default_post.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/resources.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/moc.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/uic.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/file_copies.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/yacc.prf \
		/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/lex.prf \
		basiclayouts.pro \
		/opt/qt5.9.2/5.9.2/gcc_64/lib/libQt5Widgets.prl \
		/opt/qt5.9.2/5.9.2/gcc_64/lib/libQt5Gui.prl \
		/opt/qt5.9.2/5.9.2/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile basiclayouts.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/spec_pre.prf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/unix.conf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/linux.conf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/sanitize.conf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/gcc-base.conf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/g++-base.conf:
/scratch/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/qconfig.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt_config.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/spec_post.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/toolchain.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/default_pre.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/default_post.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qml_debug.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/warn_on.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qt.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/resources.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/moc.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/uic.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/unix/thread.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/qmake_use.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/file_copies.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/exceptions.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/yacc.prf:
/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/lex.prf:
basiclayouts.pro:
/opt/qt5.9.2/5.9.2/gcc_64/lib/libQt5Widgets.prl:
/opt/qt5.9.2/5.9.2/gcc_64/lib/libQt5Gui.prl:
/opt/qt5.9.2/5.9.2/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile basiclayouts.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: git Makefile $(TARGET) TestIRCServer

TestIRCServer: TestIRCServer.c
	g++ -g -o TestIRCServer TestIRCServer.c

git:
	git add -A  >> .local.git.out
	git commit -a -m "Make IRCclient" >> .local.git.out

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h $(DISTDIR)/
	$(COPY_FILE) --parents dialog.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) $(TARGET) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/qt5.9.2/5.9.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: /opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QDialog \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtcore-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qflags.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qversiontagging.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtgui-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstring.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qchar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qiterator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpair.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrect.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsize.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrgba64.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvector.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qregion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qline.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qimage.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhash.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfont.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlocale.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qset.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qurl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfile.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtouchdevice.h \
		dialog.h \
		moc_predefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/bin/moc
	/opt/qt5.9.2/5.9.2/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/opt/qt5.9.2/5.9.2/gcc_64/mkspecs/linux-g++ -I/u/data/u98/cs240/2017Fall/lab11-irc-gui-qt/lab11-src/layout2 -I/opt/qt5.9.2/5.9.2/gcc_64/include -I/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets -I/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui -I/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialog.h -o moc_dialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

dialog.o: dialog.cpp /opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QtWidgets \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QtWidgetsDepends \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QtCore \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QtCoreDepends \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtcore-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qflags.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qversiontagging.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstractanimation.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstring.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qchar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qiterator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpair.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhash.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlocale.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvector.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qset.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstractproxymodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstractstate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qabstracttransition.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qanimationgroup.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qarraydataops.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbasictimer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbitarray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbuffer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearraymatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcache.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcollator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcommandlineoption.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcommandlineparser.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcryptographichash.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdatetime.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qelapsedtimer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdir.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfileinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfile.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdiriterator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qeasingcurve.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qendian.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qeventtransition.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qexception.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfactoryinterface.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfileselector.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QObject \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QStringList \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfilesystemwatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfinalstate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfuture.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfutureinterface.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrunnable.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qresultstore.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfuturesynchronizer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfuturewatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhistorystate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qidentityproxymodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qisenum.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qitemselectionmodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qjsonarray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qjsondocument.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qjsonobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlibrary.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlibraryinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qversionnumber.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qline.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlinkedlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlockfile.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qloggingcategory.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmath.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmetaobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmimedata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmimedatabase.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmimetype.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qoperatingsystemversion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qparallelanimationgroup.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpauseanimation.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qplugin.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpluginloader.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qprocess.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpropertyanimation.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvariantanimation.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qqueue.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qreadwritelock.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrect.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsize.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qregularexpression.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qresource.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsavefile.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qscopedvaluerollback.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsemaphore.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsettings.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedmemory.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsignalmapper.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsignaltransition.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsocketnotifier.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstack.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstandardpaths.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstatemachine.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstorageinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringlistmodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsystemsemaphore.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtemporarydir.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QScopedPointer \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtemporaryfile.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtextboundaryfinder.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtextcodec.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qthread.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qthreadpool.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qthreadstorage.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtimeline.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtimer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtimezone.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtranslator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtypetraits.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qurl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/quuid.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qwaitcondition.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qwineventnotifier.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qxmlstream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtcoreversion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QtGui \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QtGuiDepends \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtgui-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrgba64.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qregion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextformat.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfont.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpen.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qimage.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextoption.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qglyphrun.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrawfont.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontdatabase.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextcursor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextdocument.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qaccessible.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qaccessiblebridge.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qaccessibleobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qaccessibleplugin.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qbackingstore.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindow.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QEvent \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QMargins \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QRect \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qsurface.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qsurfaceformat.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qicon.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qbitmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qclipboard.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qdesktopservices.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qdrag.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qgenericmatrix.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qgenericplugin.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qgenericpluginfactory.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qinputmethod.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qiconengine.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qiconengineplugin.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qimageiohandler.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qimagereader.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qimagewriter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qmatrix4x4.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qvector3d.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qvector4d.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qquaternion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qmovie.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qoffscreensurface.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopengl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qt_windows.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglext.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglbuffer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopengldebug.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglextrafunctions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglfunctions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglframebufferobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglpaintdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglpixeltransferoptions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QSharedDataPointer \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglshaderprogram.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopengltexture.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopengltextureblitter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QMatrix3x3 \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QMatrix4x4 \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopengltimerquery.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qopenglwindow.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QPaintDeviceWindow \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QWindow \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QPaintDevice \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QOpenGLContext \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QImage \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpagedpaintdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpagelayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpagesize.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpaintengine.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpainter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpdfwriter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpicture.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpictureformatplugin.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixmapcache.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrasterwindow.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qscreen.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QList \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QSize \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QSizeF \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QTransform \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qsessionmanager.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qstandarditemmodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qstatictext.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qstylehints.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qsyntaxhighlighter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextdocumentfragment.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextdocumentwriter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtextlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtexttable.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qvalidator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtguiversion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qabstractbutton.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstyleoption.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qslider.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstyle.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtabbar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qrubberband.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qframe.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qabstractitemview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qaccessiblewidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qaction.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qboxlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlayoutitem.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgridlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qbuttongroup.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcalendarwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcheckbox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcolordialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcolormap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcolumnview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcombobox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qpushbutton.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcommonstyle.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qcompleter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdatawidgetmapper.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdatetimeedit.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdial.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdialogbuttonbox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdirmodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qfileiconprovider.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdockwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdrawutil.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qerrormessage.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qfiledialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qfilesystemmodel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qfocusframe.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qfontcombobox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qfontdialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qformlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QLayout \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgesture.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgesturerecognizer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsanchorlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsitem.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicslayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicslayoutitem.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicseffect.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsgridlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsitemanimation.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicslinearlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsproxywidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicswidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsscene.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicssceneevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicstransform.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/QVector3D \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgraphicsview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qscrollarea.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qgroupbox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qheaderview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qinputdialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlineedit.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qitemdelegate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qitemeditorfactory.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qkeyeventtransition.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qkeysequenceedit.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlabel.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlcdnumber.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlistview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qlistwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmdiarea.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmdisubwindow.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmenu.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmenubar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qmouseeventtransition.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qopenglwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QWidget \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qplaintextedit.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtextedit.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qprogressbar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qprogressdialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qproxystyle.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QCommonStyle \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qradiobutton.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qscrollbar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qscroller.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QPointF \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QScrollerProperties \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qscrollerproperties.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QMetaType \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/QVariant \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qshortcut.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsizegrip.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qspinbox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsplashscreen.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsplitter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstackedlayout.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstackedwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstatusbar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstyleditemdelegate.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstylefactory.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstylepainter.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qstyleplugin.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtableview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtablewidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtextbrowser.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtoolbar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtoolbox.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtoolbutton.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtooltip.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtreeview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtreewidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtreewidgetitemiterator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qundogroup.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qundostack.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qundoview.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qwhatsthis.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qwidgetaction.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qwizard.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgetsversion.h \
		dialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QDialog
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

main.o: main.cpp /opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QApplication \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qapplication.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qglobal.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qconfig.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtcore-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsysinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlogging.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qflags.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmutex.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qnumeric.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qversiontagging.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtgui-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstring.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qchar.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrefcount.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qnamespace.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qarraydata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobject.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qalgorithms.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qiterator.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpair.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringlist.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qregexp.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcoreevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmetatype.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qobject_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qeventloop.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qpoint.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsize.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qcursor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qwidget.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmargins.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qrect.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpalette.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qcolor.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrgb.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qrgba64.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qbrush.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvector.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qmatrix.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpolygon.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qregion.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdatastream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qiodevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qline.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtransform.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpainterpath.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qimage.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixelformat.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qpixmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qshareddata.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qhash.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfont.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qfontinfo.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qkeysequence.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qevent.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qvariant.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qmap.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qdebug.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qtextstream.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qlocale.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qset.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qurl.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qurlquery.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfile.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtCore/qfiledevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qvector2d.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qguiapplication.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtGui/qinputmethod.h \
		dialog.h \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/QDialog \
		/opt/qt5.9.2/5.9.2/gcc_64/include/QtWidgets/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qt5.9.2/Examples/Qt-5.9.2/widgets/layouts/basiclayouts || mkdir -p $(INSTALL_ROOT)/opt/qt5.9.2/Examples/Qt-5.9.2/widgets/layouts/basiclayouts
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/qt5.9.2/Examples/Qt-5.9.2/widgets/layouts/basiclayouts/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/qt5.9.2/Examples/Qt-5.9.2/widgets/layouts/basiclayouts/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qt5.9.2/Examples/Qt-5.9.2/widgets/layouts/basiclayouts/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

